apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fl-client
  template:
    metadata:
      labels:
        app: fl-client
    spec:
      containers:
      - name: fl-client
        image: fl-client-image:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"